name: Update Bad IP List

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Pull IPs from multiple sources and update bad_ips.csv
      run: |
        echo "Fetching IPs..."

        # Create temp files
        mkdir -p feeds
        cd feeds

        # Fetch from AbuseIPDB (free sample feed, replace with real API if needed)
        curl -s https://feodotracker.abuse.ch/downloads/ipblocklist.csv | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' > feodo.txt

        # Fetch from Spamhaus DROP
        curl -s https://www.spamhaus.org/drop/drop.txt | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' >> spamhaus.txt

        # Fetch from Emerging Threats
        curl -s https://rules.emergingthreats.net/blockrules/compromised-ips.txt >> et.txt

        # Combine and deduplicate
        cat *.txt | sort | uniq > ../bad_ips.csv

        cd ..

   - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add bad_ips.csv

        if ! git diff --cached --quiet; then
          git commit -m "Daily update of bad IPs"
          git push
        else
          echo "No changes in bad_ips.csv — skipping commit."
        fi
